name: todo_app
description: "A new Flutter project."
# test The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.7
  flutter_adaptive_scaffold: ^0.3.1
  uuid: ^4.5.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  shimmer_animation: ^2.2.1



  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

